[tool.ruff]
select = ["E", "F", "W", "I"]
ignore = ["W504"]
line-length = 88
exclude = ["src/__pycache__", ".venv", "notebooks", "tests"]

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true
no_implicit_optional = true

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report=html"
